import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { URLContextProvider } from "@/context/urlContext";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});
export const metadata = {
  title: "URL Shortner",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jakarta}`}>
        <URLContextProvider>
          <div className="w-full min-h-screen bg-gradient-to-b from-slate-950 to-slate-800">
            <Toaster/>
            <Header />
            {children}
            <Footer />
          </div>
        </URLContextProvider>
      </body>
    </html>
  );
}
